//! The workflow runner (spec 09): drive the pipeline end to end, gating each phase
//! boundary through a [`Gate`], persisting each artifact, and emerging with the
//! swarm-ready subtask board from the final phase.
//!
//! Two gating modes share one loop. The autonomous default ([`run_workflow`])
//! approves every phase via [`AutoApprove`]; an interactive run supplies a gate that
//! reads a human's approve/revise/send-back/abort decision at each checkpoint. The
//! gate is harness-owned — the loop, not the model, applies the decision.

use std::path::Path;

use sc_model::ModelBackend;
use sc_proto::Result;
use sc_swarm::{parse_subtasks_on_stack, TaskBoard};

use crate::engine::generate_phase;
use crate::gate::{AutoApprove, Decision, Gate};
use crate::phase::Phase;
use crate::policy::ThinkPolicy;
use crate::stack::ProjectStack;
use crate::state::{plan_dir, save, WorkflowState};

/// How much of the pipeline to run, and whether to write frozen tests.
///
/// The default ([`WorkflowMode::full_tdd`]) is the original behavior: all six phases, and the
/// approved stage-breakdown drives worker-written frozen tests. [`WorkflowMode::plan_only`] is
/// the "structured design, no TDD" mode the desktop app's Execute uses: run the design phases
/// through the stage breakdown, then STOP — no test writing, no decomposition, no build — so
/// the user reviews specs → architecture → layout → breakdown before anything is built.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkflowMode {
    /// Skip writing frozen tests after the stage-breakdown phase.
    pub skip_tests: bool,
    /// Stop the pipeline after this phase is approved (inclusive). `None` runs to the end.
    pub stop_after: Option<Phase>,
}

impl WorkflowMode {
    /// The full six-phase TDD pipeline: writes frozen tests, runs to work-decomposition.
    pub fn full_tdd() -> Self {
        Self {
            skip_tests: false,
            stop_after: None,
        }
    }

    /// Structured design only: run through the stage breakdown, write no tests, stop before
    /// decomposition/build. The Execute-plan flow — produce a reviewable plan, don't build yet.
    pub fn plan_only() -> Self {
        Self {
            skip_tests: true,
            stop_after: Some(Phase::StageBreakdown),
        }
    }
}

impl Default for WorkflowMode {
    fn default() -> Self {
        Self::full_tdd()
    }
}

/// What a completed workflow yields.
#[derive(Debug)]
pub struct WorkflowOutcome {
    /// The full artifact chain (all approved), persisted under the plan dir.
    pub state: WorkflowState,
    /// The subtask board parsed from the final (work-decomposition) phase — the
    /// swarm's input. Empty board if the model produced nothing parseable.
    pub board: TaskBoard,
    /// The test files the workers wrote from the Phase-4 coverage plan, already
    /// persisted to `workspace`. These are the frozen contract the implementation
    /// swarm must satisfy.
    pub test_files: Vec<String>,
    /// Whether the human aborted at a checkpoint. When true the pipeline stopped
    /// early: `state` holds the approved-so-far artifacts (kept, per spec 09) and
    /// `board`/`test_files` reflect only what was reached.
    pub aborted: bool,
}

/// Run the whole pipeline autonomously against `workspace`, approving every phase
/// (no human gate). This is the default mode: it proves the spec → … →
/// decomposition chain produces a board the swarm consumes. Delegates to
/// [`run_workflow_gated`] with the [`AutoApprove`] gate.
pub fn run_workflow(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
) -> Result<WorkflowOutcome> {
    run_workflow_gated(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        on_phase,
        &AutoApprove,
    )
}

/// Drive the pipeline against `workspace`, consulting `gate` at every phase
/// boundary (spec 09's macro checkpoint). Each phase is generated by `orchestrator`
/// (T1) from the prior *approved* artifacts and persisted to disk *as a draft*
/// before the gate sees it — so an interactive gate can have the human read (and,
/// for Revise, edit) the on-disk file. The gate's [`Decision`] is then applied by
/// the harness:
///
/// - **Approve** — accept the draft and advance.
/// - **Revise** — re-read the (human-edited) file from disk, accept that.
/// - **Send back** — drop this phase and everything downstream, regenerate from the
///   target phase (`invalidate_from`).
/// - **Abort** — stop now; approved artifacts are kept and the outcome is flagged.
///
/// Only an *approved* Phase-4 (stage-breakdown) artifact triggers the worker test
/// writing, so revised coverage plans drive the frozen tests and a send-back that
/// later re-approves Phase 4 regenerates them.
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_gated(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    run_workflow_moded(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        WorkflowMode::full_tdd(),
        on_phase,
        gate,
    )
}

/// The core pipeline driver, parameterized by [`WorkflowMode`] — the full-TDD default and the
/// plan-only Execute flow share this one loop. `mode.stop_after` ends the run once that phase
/// is approved (plan-only stops at the stage breakdown); `mode.skip_tests` suppresses the
/// worker test-writing (plan-only produces a design, not a frozen contract).
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_moded(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    mode: WorkflowMode,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    // Ground the task in reality BEFORE the first phase: a workflow phase is a direct model call
    // that otherwise sees only the task string — so with just "implement PLAN-lakes.md" the
    // orchestrator designed a generic module tree that ignored the plan AND the real files
    // (observed live 2026-07-14: it invented src/lakes/*.rs, never touching the plan's
    // gen/terrain.rs / render.rs). Inject the plan's full body and a survey of the files that
    // actually exist, so every phase designs against THIS plan and THIS codebase.
    let grounded = ground_task(task, workspace);
    let mut state = WorkflowState::new(grounded);
    let mut test_files = Vec::new();
    let mut aborted = false;
    // Detect the project's language once, so every phase prompt speaks it (a Rust cargo repo
    // gets Rust rules, not the Python/Flask default). Derived from the workspace, not stored in
    // the serializable state.
    let stack = ProjectStack::detect(workspace);

    while let Some(phase) = state.next_phase() {
        let artifact = generate_phase(orchestrator, phase, &state, think, stack);
        // Fail loudly on an empty artifact (after the engine's retries) rather than
        // chaining a broken plan downstream — the usual cause is a dead/unreachable
        // orchestrator backend (spec 00 — fail clearly, don't corrupt silently).
        if artifact.content.trim().is_empty() {
            return Err(sc_proto::DcError::Eval(format!(
                "workflow: the {} phase produced no content — is the orchestrator backend up?",
                phase.title()
            )));
        }
        on_phase(phase, &artifact.content);
        // Persist as a draft first, so the gate (and a human editing the file for a
        // Revise) is looking at exactly what's on disk.
        state.set(artifact);
        save(workspace, &state)?;

        match gate.decide(phase, state.artifact(phase).expect("just set")) {
            Decision::Approve => {}
            Decision::Revise => {
                // The human edited the artifact file on disk; re-read it as the
                // accepted content. Fall back to the draft if the file is gone.
                let edited = std::fs::read_to_string(plan_dir(workspace).join(phase.filename()))
                    .unwrap_or_else(|_| artifact_content(&state, phase));
                state.set(crate::state::Artifact::draft(phase, edited));
            }
            Decision::SendBack { target, notes } => {
                // Bounce to an earlier (or this) phase: drop it and everything
                // downstream so they regenerate from the revised upstream. Feedback
                // notes ground the regeneration.
                state.invalidate_from(target);
                if let Some(notes) = notes {
                    state.set_feedback(target, notes);
                }
                save(workspace, &state)?;
                // Test files written from a now-dropped coverage plan are stale.
                if target.index() <= Phase::StageBreakdown.index() {
                    test_files.clear();
                }
                continue;
            }
            Decision::Abort => {
                aborted = true;
                break;
            }
        }

        // Accepted (Approve or Revise): freeze it as grounding for the next phase.
        state.approve(phase);
        save(workspace, &state)?;

        // After the coverage plan is approved, have workers write the tests so
        // they exist on disk for the implementation phases to target. Skipped in the
        // plan-only mode (Execute produces a design, not a frozen test contract).
        if phase == Phase::StageBreakdown && !mode.skip_tests {
            let coverage = crate::coverage::parse_coverage(&artifact_content(&state, phase));
            let written = crate::testwriter::write_tests(worker, &coverage);
            test_files = crate::testwriter::persist_tests(workspace, &written)?;
        }

        // Stop-at-phase (plan-only stops once the stage breakdown is approved): the design is
        // done and the user reviews before anything is built. Downstream phases are simply not
        // generated — the state holds the approved-so-far chain.
        if mode.stop_after == Some(phase) {
            break;
        }
    }

    let board = board_from(&state, &test_files, stack);
    Ok(WorkflowOutcome {
        state,
        board,
        test_files,
        aborted,
    })
}

/// Augment the task with the grounding every phase needs: the full body of a `PLAN-*.md` the
/// task references (so the design follows the actual plan, not a guess from its filename), and
/// a survey of the source files that already exist (so it edits real files like `gen/terrain.rs`
/// instead of inventing a fresh module tree). Both are read from `workspace`; if there's no plan
/// reference or no files, that section is simply omitted.
fn ground_task(task: &str, workspace: &Path) -> String {
    let mut out = String::from(task);

    if let Some((name, body)) = referenced_plan(task, workspace) {
        out.push_str(&format!(
            "\n\n=== The feature plan you are designing for ({name}) — follow it ===\n{body}\n\
             Design for exactly this plan: its Approach, its Files-to-touch, and its Steps. Do \
             NOT invent a different structure or ignore the files it names."
        ));

        // Inject the FULL CONTENTS of the existing files the plan says it will touch. Without
        // this the design phases saw only filenames and invented an architecture that doesn't
        // exist — an `ElevationField` struct, a `lake_generator` module, an `Elevation` enum —
        // so every downstream build stage stalled hunting fictional symbols. Showing the real
        // code makes the architecture/layout/breakdown reference types that actually exist.
        let touched = plan_touched_files(&body, workspace);
        for f in touched.iter().take(6) {
            if let Ok(src) = std::fs::read_to_string(workspace.join(f)) {
                let clipped = clip_chars(&src, 12_000);
                out.push_str(&format!(
                    "\n\n=== EXISTING contents of {f} (design against the REAL types/functions \
                     here; the plan may name things that do not exist — use what is actually in \
                     this code) ===\n{clipped}\n=== end {f} ==="
                ));
            }
        }
    }

    let files = sc_core::source_files(workspace);
    if !files.is_empty() {
        out.push_str(
            "\n\n=== Source files that ALREADY EXIST in this project (edit these; do not \
             reinvent the layout) ===\n",
        );
        for f in files.iter().take(200) {
            out.push_str("  ");
            out.push_str(f);
            out.push('\n');
        }
        out.push_str(
            "Ground the architecture and layout in these real files and the plan's \
             Files-to-touch — new files only where the plan calls for them.",
        );
    }

    out
}

/// If `task` names a feature spec that exists in `workspace` — `specs/<slug>.md` or a legacy
/// `PLAN-<slug>.md` — return `(name, contents)`. Mirrors the agent loop's `referenced_plan` so
/// the workflow pins the same spec.
fn referenced_plan(task: &str, workspace: &Path) -> Option<(String, String)> {
    let token = task
        .split(|c: char| c.is_whitespace() || matches!(c, '`' | '"' | '\'' | '(' | ')' | ','))
        .map(|t| t.trim_end_matches('.'))
        .find(|t| {
            let norm = t.replace('\\', "/");
            let low = norm.to_ascii_lowercase();
            (low.starts_with("specs/") && low.ends_with(".md"))
                || {
                    let up = norm.to_ascii_uppercase();
                    up.starts_with("PLAN-") && up.ends_with(".MD")
                }
        })?;
    let body = std::fs::read_to_string(workspace.join(token)).ok()?;
    if body.trim().is_empty() {
        return None;
    }
    Some((token.to_string(), body))
}

/// Extract the existing source files a plan says it will touch, so their real contents can
/// ground the design. Scans the plan body for path-shaped tokens (ending in a code extension)
/// and resolves each to a REAL file in the project — matching by path suffix, because a plan
/// often names a crate-relative path (`gen/terrain.rs`) while the file lives deeper
/// (`crates/city/src/gen/terrain.rs`). Returns workspace-relative paths, deduped, order-preserving.
fn plan_touched_files(plan_body: &str, workspace: &Path) -> Vec<String> {
    const EXTS: [&str; 8] = [".rs", ".py", ".js", ".ts", ".go", ".java", ".css", ".html"];
    let all = sc_core::source_files(workspace); // real files, workspace-relative
    let mut out: Vec<String> = Vec::new();
    for tok in plan_body.split(|c: char| c.is_whitespace() || matches!(c, '`' | '"' | '\'' | '(' | ')' | ',' | ':')) {
        let t = tok.trim().trim_end_matches(&['.', ';'][..]);
        if t.is_empty() {
            continue;
        }
        let lower = t.to_ascii_lowercase();
        if !EXTS.iter().any(|e| lower.ends_with(e)) {
            continue;
        }
        // Resolve: exact match, else a real file whose path ends with this token (with a '/'
        // boundary so "terrain.rs" doesn't match "myterrain.rs").
        let norm = t.replace('\\', "/");
        let resolved = if workspace.join(&norm).is_file() {
            Some(norm.clone())
        } else {
            all.iter()
                .find(|f| {
                    let fp = f.replace('\\', "/");
                    fp == norm || fp.ends_with(&format!("/{norm}"))
                })
                .cloned()
        };
        if let Some(r) = resolved {
            if !out.contains(&r) {
                out.push(r);
            }
        }
    }
    out
}

/// Clip `s` to at most `max` chars on a char boundary, noting the truncation. Keeps the HEAD
/// (imports, type/struct decls, signatures — what a design needs), which is what sits at the
/// top of a source file.
fn clip_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let end = s
        .char_indices()
        .nth(max)
        .map(|(i, _)| i)
        .unwrap_or(s.len());
    format!("{}\n… (file truncated — first {max} chars shown)", &s[..end])
}

fn artifact_content(state: &WorkflowState, phase: Phase) -> String {
    state
        .artifact(phase)
        .map(|a| a.content.clone())
        .unwrap_or_default()
}

/// Parse the work-decomposition artifact into the swarm's [`TaskBoard`] (spec 09
/// → spec 08 input contract), then drop any non-implementation subtasks the model
/// slipped in: ones that target a frozen test file, or that name no files at all
/// (e.g. a "run the tests" step — the harness verifies, that's not worker work).
/// Tests are already written and frozen; the swarm only implements.
fn board_from(state: &WorkflowState, test_files: &[String], stack: ProjectStack) -> TaskBoard {
    let is_test = |f: &str| {
        let n = f.replace('\\', "/");
        test_files.iter().any(|t| t.replace('\\', "/") == n)
    };
    // Parse against THIS project's stack, so the drift filter keeps its own files (the bug: the
    // filter was hardcoded to Python and dropped every .rs subtask → empty board → nothing built).
    let subtasks: Vec<_> = state
        .artifact(Phase::WorkDecomposition)
        .map(|a| parse_subtasks_on_stack(&a.content, stack.on_stack_exts()))
        .unwrap_or_default()
        .into_iter()
        .filter(|s| !s.files.is_empty() && !s.files.iter().all(|f| is_test(f)))
        .collect();
    TaskBoard::new(subtasks)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::Artifact;
    use sc_model::{Capabilities, GenerateRequest, GenerateResponse, ToolCalling};
    use std::sync::Mutex;

    #[test]
    fn ground_task_injects_the_plan_body_and_the_real_file_survey() {
        // The live regression: without grounding, a phase saw only "implement PLAN-lakes.md"
        // and designed a generic module tree that ignored the plan and the real files. Grounding
        // must put the plan's BODY and the existing source files into the task.
        let ws = temp("ground");
        std::fs::write(ws.join("Cargo.toml"), "[package]").unwrap();
        std::fs::create_dir_all(ws.join("gen")).unwrap();
        std::fs::write(ws.join("gen/terrain.rs"), "pub fn gen() {}").unwrap();
        std::fs::write(ws.join("render.rs"), "pub fn draw() {}").unwrap();
        std::fs::write(
            ws.join("PLAN-lakes.md"),
            "## Plan: lakes\n**Approach:** flood-fill basins\n**Files to touch:**\n- gen/terrain.rs",
        )
        .unwrap();

        let grounded = ground_task("Design how to implement PLAN-lakes.md.", &ws);
        // The plan body is present (not just its name).
        assert!(grounded.contains("flood-fill basins"), "plan body injected: {grounded}");
        assert!(grounded.contains("follow it"), "framed to follow the plan");
        // The real files are surveyed, so the model edits them instead of inventing a layout.
        assert!(grounded.contains("gen/terrain.rs"), "real file surveyed");
        assert!(grounded.contains("render.rs"), "real file surveyed");
        assert!(grounded.contains("ALREADY EXIST"), "survey framing present");
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn ground_task_injects_the_real_contents_of_the_plans_touched_files() {
        // The invented-architecture bug: with only a file LIST, the design phases hallucinated
        // an `ElevationField` struct that doesn't exist. Grounding must inject the real file
        // CONTENTS so the design references types that are actually there.
        let ws = temp("ground-contents");
        std::fs::write(ws.join("Cargo.toml"), "[package]").unwrap();
        std::fs::create_dir_all(ws.join("gen")).unwrap();
        std::fs::write(
            ws.join("gen/terrain.rs"),
            "pub struct Terrain { seed: u64 }\nimpl Terrain { pub fn elevation(&self) -> f32 { 0.0 } }",
        )
        .unwrap();
        std::fs::write(
            ws.join("PLAN-lakes.md"),
            "## Plan\n**Files to touch:**\n- `gen/terrain.rs` (update: add lakes)",
        )
        .unwrap();

        let g = ground_task("Design PLAN-lakes.md.", &ws);
        assert!(g.contains("EXISTING contents of gen/terrain.rs"), "real file injected");
        assert!(g.contains("pub struct Terrain"), "real type shown so the design uses it");
        assert!(g.contains("fn elevation"), "real method shown");
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn plan_touched_files_resolves_crate_relative_paths_by_suffix() {
        // The real bug: the plan names `gen/terrain.rs` but the file lives at
        // crates/city/src/gen/terrain.rs — so exact join fails and grounding never fires.
        // Suffix resolution finds the real file.
        let ws = temp("touched");
        std::fs::create_dir_all(ws.join("crates/city/src/gen")).unwrap();
        std::fs::write(ws.join("crates/city/src/gen/terrain.rs"), "x").unwrap();
        std::fs::write(ws.join("crates/city/src/render.rs"), "x").unwrap();
        let body = "- `gen/terrain.rs` (update)\n- render.rs (logic)\n- gen/missing.rs (nope)";
        let mut got = plan_touched_files(body, &ws);
        got.sort();
        assert_eq!(
            got,
            vec![
                "crates/city/src/gen/terrain.rs".to_string(),
                "crates/city/src/render.rs".to_string(),
            ]
        );
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn ground_task_is_a_noop_without_a_plan_or_files() {
        // The Python eval ladder builds from an empty dir with no PLAN reference — grounding
        // must leave that task untouched so the ladder is unaffected.
        let ws = temp("ground-empty");
        let task = "build a counter API";
        assert_eq!(ground_task(task, &ws), task);
        let _ = std::fs::remove_dir_all(&ws);
    }

    /// A backend that answers each phase by matching its system prompt, and emits a
    /// valid subtask array for the decomposition phase.
    struct PhaseScripted {
        replies: Mutex<Vec<(&'static str, &'static str)>>,
    }
    impl ModelBackend for PhaseScripted {
        fn name(&self) -> &str {
            "phase-scripted"
        }
        fn capabilities(&self) -> Capabilities {
            Capabilities {
                max_context_tokens: 8192,
                tool_calling: ToolCalling::None,
                on_device: false,
            }
        }
        fn generate(&self, req: &GenerateRequest) -> sc_proto::Result<GenerateResponse> {
            let instr = req
                .messages
                .iter()
                .map(|m| m.content.as_str())
                .collect::<Vec<_>>()
                .join("\n");
            let replies = self.replies.lock().unwrap();
            for (key, body) in replies.iter() {
                if instr.contains(key) {
                    return Ok(GenerateResponse {
                        content: body.to_string(),
                    });
                }
            }
            Ok(GenerateResponse {
                content: "(nothing)".to_string(),
            })
        }
    }

    fn temp(tag: &str) -> std::path::PathBuf {
        let n = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let d = std::env::temp_dir().join(format!("dc-wf-run-{tag}-{n}"));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn runs_all_phases_and_emits_a_board() {
        let backend = PhaseScripted {
            replies: Mutex::new(vec![
                ("crisp spec", "# Specs\ngoals"),
                ("high-level architecture", "# Architecture\nshape"),
                ("concrete project layout", "# Layout\nfiles"),
                (
                    "plan the TESTS",
                    r#"[{"file":"test_a.py","covers":"a works"}]"#,
                ),
                // The test-writer worker call (system prompt says "You write a runnable unit-test file").
                ("pytest test file", "def test_a():\n    assert a() == 1"),
                ("ordered plan", "# Plan\nsteps"),
                (
                    "per source file",
                    r#"[{"id":"t1","goal":"do a","files":["a.py"]},{"id":"t2","goal":"do b","files":["b.py"]}]"#,
                ),
            ]),
        };
        let ws = temp("all");
        // This exercises the Python TDD ladder path — mark the workspace Python explicitly now
        // that a bare workspace detects as Unknown (a generic project) rather than Python.
        std::fs::write(ws.join("requirements.txt"), "flask\n").unwrap();
        let seen = std::cell::RefCell::new(Vec::new());
        // Same backend stands in for both orchestrator and worker here.
        let outcome = run_workflow(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|p, _| seen.borrow_mut().push(p),
        )
        .unwrap();

        // All six phases ran, in order, and the workflow is complete.
        assert_eq!(seen.into_inner(), Phase::ALL.to_vec());
        assert!(outcome.state.is_complete());
        // The decomposition produced a swarm board with two subtasks.
        assert_eq!(outcome.board.len(), 2);
        // A worker wrote the test file from the coverage plan, and it's on disk.
        assert_eq!(outcome.test_files, vec!["test_a.py"]);
        let test_body = std::fs::read_to_string(ws.join("test_a.py")).unwrap();
        assert!(test_body.contains("def test_a"));
        // Artifacts persisted as reviewable Markdown.
        let arch = std::fs::read_to_string(crate::state::plan_dir(&ws).join("02-architecture.md"))
            .unwrap();
        assert!(arch.contains("shape"));
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn plan_only_stops_at_the_stage_breakdown_and_writes_no_tests() {
        // The Execute-plan flow on a Rust project: run specs → architecture → layout → stage
        // breakdown (as an ordered design, not tests), then STOP. No test files, no
        // decomposition, no board — the user reviews before anything is built.
        let backend = PhaseScripted {
            replies: Mutex::new(vec![
                ("crisp spec", "# Specs\ngoals"),
                ("high-level architecture", "# Architecture\nshape"),
                ("concrete project layout", "# Layout\nfiles"),
                // Rust stack → the stage-breakdown system prompt says "ordered set of small
                // implementation stages", so key off that instead of "plan the TESTS".
                ("ordered set of small implementation stages", "# Breakdown\n1. detect basins"),
            ]),
        };
        let ws = temp("plan-only");
        // Make it a Rust project so ProjectStack::detect → Rust (non-TDD breakdown path).
        std::fs::write(ws.join("Cargo.toml"), "[package]\nname=\"city\"").unwrap();
        let seen = std::cell::RefCell::new(Vec::new());
        let outcome = run_workflow_moded(
            &backend,
            &backend,
            "add lakes to the terrain",
            &ws,
            ThinkPolicy::default(),
            WorkflowMode::plan_only(),
            &|p, _| seen.borrow_mut().push(p),
            &AutoApprove,
        )
        .unwrap();

        // Ran exactly the four design phases, stopping at the stage breakdown.
        assert_eq!(
            seen.into_inner(),
            vec![
                Phase::Specs,
                Phase::Architecture,
                Phase::Layout,
                Phase::StageBreakdown
            ]
        );
        // No tests written, no decomposition board.
        assert!(outcome.test_files.is_empty(), "plan-only writes no frozen tests");
        assert_eq!(outcome.board.len(), 0, "no decomposition/build in plan-only");
        assert!(!outcome.aborted);
        // The design artifacts are on disk for review.
        let breakdown =
            std::fs::read_to_string(crate::state::plan_dir(&ws).join("04-stage-breakdown.md"))
                .unwrap();
        assert!(breakdown.contains("detect basins"));
        // The later phases were never generated.
        assert!(outcome.state.artifact(Phase::WorkDecomposition).is_none());
        let _ = std::fs::remove_dir_all(&ws);
    }

    /// A full scripted backend that answers every phase + the test-writer worker.
    fn full_backend() -> PhaseScripted {
        PhaseScripted {
            replies: Mutex::new(vec![
                ("crisp spec", "# Specs\ngoals"),
                ("high-level architecture", "# Architecture\nshape"),
                ("concrete project layout", "# Layout\nfiles"),
                (
                    "plan the TESTS",
                    r#"[{"file":"test_a.py","covers":"a works"}]"#,
                ),
                ("pytest test file", "def test_a():\n    assert a() == 1"),
                ("ordered plan", "# Plan\nsteps"),
                (
                    "per source file",
                    r#"[{"id":"t1","goal":"do a","files":["a.py"]}]"#,
                ),
            ]),
        }
    }

    /// A gate that replays a fixed script of decisions, one per checkpoint visit,
    /// recording which phases it was asked about.
    struct ScriptedGate {
        decisions: Mutex<std::collections::VecDeque<Decision>>,
        seen: Mutex<Vec<Phase>>,
    }
    impl ScriptedGate {
        fn new(decisions: Vec<Decision>) -> Self {
            Self {
                decisions: Mutex::new(decisions.into()),
                seen: Mutex::new(Vec::new()),
            }
        }
    }
    impl Gate for ScriptedGate {
        fn decide(&self, phase: Phase, _artifact: &Artifact) -> Decision {
            self.seen.lock().unwrap().push(phase);
            // Default to Approve once the script is exhausted, so a short script
            // just gates the first few phases and lets the rest sail through.
            self.decisions
                .lock()
                .unwrap()
                .pop_front()
                .unwrap_or(Decision::Approve)
        }
    }

    #[test]
    fn auto_approve_path_matches_run_workflow() {
        // run_workflow_gated with AutoApprove behaves exactly like run_workflow.
        let backend = full_backend();
        let ws = temp("gated-auto");
        let outcome = run_workflow_gated(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|_, _| {},
            &AutoApprove,
        )
        .unwrap();
        assert!(outcome.state.is_complete());
        assert!(!outcome.aborted);
        assert_eq!(outcome.board.len(), 1);
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn abort_stops_early_and_keeps_approved_artifacts() {
        let backend = full_backend();
        let ws = temp("gated-abort");
        // Approve specs + architecture, then abort at the layout checkpoint.
        let gate = ScriptedGate::new(vec![Decision::Approve, Decision::Approve, Decision::Abort]);
        let outcome = run_workflow_gated(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|_, _| {},
            &gate,
        )
        .unwrap();

        assert!(outcome.aborted);
        assert!(!outcome.state.is_complete());
        // The two approved phases survive; the aborted layout draft does not freeze.
        assert!(outcome.state.artifact(Phase::Specs).unwrap().is_approved());
        assert!(outcome
            .state
            .artifact(Phase::Architecture)
            .unwrap()
            .is_approved());
        assert!(!outcome.state.artifact(Phase::Layout).unwrap().is_approved());
        // Never reached decomposition, so no board.
        assert_eq!(outcome.board.len(), 0);
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn revise_reads_the_edited_file_from_disk() {
        let backend = full_backend();
        let ws = temp("gated-revise");
        // A gate that, on the very first (Specs) checkpoint, edits the on-disk file
        // and asks for a Revise; everything else approves.
        struct EditingGate {
            ws: std::path::PathBuf,
            edited: Mutex<bool>,
        }
        impl Gate for EditingGate {
            fn decide(&self, phase: Phase, _a: &Artifact) -> Decision {
                if phase == Phase::Specs && !*self.edited.lock().unwrap() {
                    std::fs::write(
                        plan_dir(&self.ws).join(phase.filename()),
                        "# Specs\nHUMAN EDITED",
                    )
                    .unwrap();
                    *self.edited.lock().unwrap() = true;
                    return Decision::Revise;
                }
                Decision::Approve
            }
        }
        let gate = EditingGate {
            ws: ws.clone(),
            edited: Mutex::new(false),
        };
        let outcome = run_workflow_gated(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|_, _| {},
            &gate,
        )
        .unwrap();

        // The approved specs artifact is the human's edited content, not the draft.
        let specs = outcome.state.artifact(Phase::Specs).unwrap();
        assert!(specs.is_approved());
        assert!(specs.content.contains("HUMAN EDITED"));
        assert!(outcome.state.is_complete());
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn send_back_regenerates_with_feedback_and_completes() {
        let ws = temp("gated-sendback");
        // Count how many times the architecture phase is generated: a send-back from
        // Layout to Architecture should regenerate it.
        let arch_calls = std::cell::RefCell::new(0u32);
        let saw_feedback = std::cell::RefCell::new(false);
        {
            let backend = full_backend();
            // Gate: approve specs + architecture, then at the Layout checkpoint send
            // back to Architecture with a note. After that, approve everything.
            let gate = ScriptedGate::new(vec![
                Decision::Approve, // specs
                Decision::Approve, // architecture (1st)
                Decision::SendBack {
                    target: Phase::Architecture,
                    notes: Some("make it event-driven".to_string()),
                }, // layout → bounce
            ]);
            // Wrap the backend's generate to count architecture regenerations and
            // detect the feedback note reaching the prompt. We can't easily wrap the
            // trait object, so instead inspect via a custom backend.
            struct CountingBackend<'a> {
                inner: PhaseScripted,
                arch_calls: &'a std::cell::RefCell<u32>,
                saw_feedback: &'a std::cell::RefCell<bool>,
            }
            impl ModelBackend for CountingBackend<'_> {
                fn name(&self) -> &str {
                    "counting"
                }
                fn capabilities(&self) -> Capabilities {
                    self.inner.capabilities()
                }
                fn generate(&self, req: &GenerateRequest) -> sc_proto::Result<GenerateResponse> {
                    let joined: String = req.messages.iter().map(|m| m.content.clone()).collect();
                    if joined.contains("high-level architecture") {
                        *self.arch_calls.borrow_mut() += 1;
                        if joined.contains("make it event-driven") {
                            *self.saw_feedback.borrow_mut() = true;
                        }
                    }
                    self.inner.generate(req)
                }
            }
            let counting = CountingBackend {
                inner: backend,
                arch_calls: &arch_calls,
                saw_feedback: &saw_feedback,
            };
            let outcome = run_workflow_gated(
                &counting,
                &counting,
                "build it",
                &ws,
                ThinkPolicy::default(),
                &|_, _| {},
                &gate,
            )
            .unwrap();
            assert!(outcome.state.is_complete());
            assert!(!outcome.aborted);
        }
        // Architecture was generated twice (initial + after send-back), and the
        // feedback note reached the regeneration prompt.
        assert_eq!(*arch_calls.borrow(), 2);
        assert!(*saw_feedback.borrow());
        let _ = std::fs::remove_dir_all(&ws);
    }
}
