//! The pipeline driver: four public entry points over one gated loop.
//!
//! The gate is harness-owned — the loop, not the model, applies each
//! [`Decision`], so a model can never self-approve or skip a phase.

use std::path::Path;

use sc_model::ModelBackend;
use sc_proto::Result;

use crate::engine::generate_phase;
use crate::gate::{AutoApprove, Decision, Gate};
use crate::phase::Phase;
use crate::policy::ThinkPolicy;
use crate::stack::ProjectStack;
use crate::state::WorkflowState;

use super::board::{artifact_content, board_from};
use super::ground::{ground_task, referenced_plan};
use super::mode::{WorkflowMode, WorkflowOutcome};

/// Run the whole pipeline autonomously against `workspace`, approving every phase
/// (no human gate). This is the default mode: it proves the spec → … →
/// decomposition chain produces a board the swarm consumes. Delegates to
/// [`run_workflow_gated`] with the [`AutoApprove`] gate.
pub fn run_workflow(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
) -> Result<WorkflowOutcome> {
    run_workflow_gated(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        on_phase,
        &AutoApprove,
    )
}

/// Drive the pipeline against `workspace`, consulting `gate` at every phase
/// boundary (spec 09's macro checkpoint). Each phase is generated by `orchestrator`
/// (T1) from the prior *approved* artifacts and persisted to disk *as a draft*
/// before the gate sees it — so an interactive gate can have the human read (and,
/// for Revise, edit) the on-disk file. The gate's [`Decision`] is then applied by
/// the harness:
///
/// - **Approve** — accept the draft and advance.
/// - **Revise** — re-read the (human-edited) file from disk, accept that.
/// - **Send back** — drop this phase and everything downstream, regenerate from the
///   target phase (`invalidate_from`).
/// - **Abort** — stop now; approved artifacts are kept and the outcome is flagged.
///
/// Only an *approved* Phase-4 (stage-breakdown) artifact triggers the worker test
/// writing, so revised coverage plans drive the frozen tests and a send-back that
/// later re-approves Phase 4 regenerates them.
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_gated(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    run_workflow_moded(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        WorkflowMode::full_tdd(),
        on_phase,
        gate,
    )
}

/// The core pipeline driver, parameterized by [`WorkflowMode`] — the full-TDD default and the
/// plan-only Execute flow share this one loop. `mode.stop_after` ends the run once that phase
/// is approved (plan-only stops at the stage breakdown); `mode.skip_tests` suppresses the
/// worker test-writing (plan-only produces a design, not a frozen contract).
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_moded(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    mode: WorkflowMode,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    // Default artifact layout: `.smart-coder/plan/` with numbered filenames. This entry point
    // has no live-token consumer (the CLI/examples stream to the plan panel via `on_phase`), so
    // pass a no-op token callback.
    run_workflow_moded_to(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        mode,
        on_phase,
        gate,
        None,
        false,
        &mut |_p, _d| {},
    )
}

/// Like [`run_workflow_moded`], but persists phase artifacts to `artifact_dir` (default
/// `.smart-coder/plan/` when `None`) with either numbered or OpenSpec filenames — so the staged
/// build can land its design in `specs/<slug>/` (spec.md, architecture.md, …) beside the spec.
///
/// `on_token(phase, delta)` receives each streamed content delta of the phase currently
/// generating, so a live UI can render the reply token-by-token (the staged run reads as alive,
/// not frozen). Callers that don't want the live view pass a no-op `&mut |_p, _d| {}`.
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_moded_to(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    mode: WorkflowMode,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
    artifact_dir: Option<&Path>,
    openspec_names: bool,
    on_token: &mut dyn FnMut(Phase, &str),
) -> Result<WorkflowOutcome> {
    // The directory phase artifacts are written to (and re-read on Revise).
    let art_dir = artifact_dir
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| crate::state::plan_dir(workspace));
    // Take the artifact directory for the life of this run (spec 19). Two surfaces
    // writing one `state.json` silently lose each other's decisions — the daemon
    // parks at a gate, the GUI opens the same project, and the phone-side approval
    // is clobbered by the GUI's next phase save with nothing logged.
    //
    // Held in a binding so it lives to the end of the function: releasing on drop
    // means a panic or an early `?` cannot strand it, and a stranded lease locks a
    // project until expiry with nothing running.
    let _lease = crate::lease::acquire(&art_dir, &crate::lease::current_owner())?;
    let save_state =
        |state: &mut WorkflowState| crate::state::save_to(&art_dir, state, openspec_names);
    // Ground the task in reality BEFORE the first phase: a workflow phase is a direct model call
    // that otherwise sees only the task string — so with just "implement PLAN-lakes.md" the
    // orchestrator designed a generic module tree that ignored the plan AND the real files
    // (observed live 2026-07-14: it invented src/lakes/*.rs, never touching the plan's
    // gen/terrain.rs / render.rs). Inject the plan's full body and a survey of the files that
    // actually exist, so every phase designs against THIS plan and THIS codebase.
    let grounded = ground_task(task, workspace);
    let mut state = WorkflowState::new(grounded);
    let mut test_files = Vec::new();
    let mut aborted = false;
    // A draft restored from a parked run, re-offered to the gate on its phase rather
    // than regenerated (spec 19). Taken once.
    let mut resumed_draft: Option<crate::state::Artifact> = None;

    // Resume from a prior run in this directory instead of regenerating it. A **Build** reuses the
    // same task (and thus the same `art_dir`) a prior **Breakdown** ran, so its approved design
    // phases are already on disk in `state.json`. Adopt them up front: `next_phase()` then skips
    // straight past specs/architecture/layout/stage-breakdown to the build, instead of re-designing
    // and re-gating them (the bug where clicking Build re-did the architecture).
    //
    // A corrupt or truncated `state.json` is an ERROR, not a fresh start (spec 19). Swallowing it
    // silently discards an entire approved design and quietly re-runs work a human already signed
    // off — the failure looks like "the tool redid everything", with nothing to point at.
    match crate::state::load_from(&art_dir) {
        Ok(Some(prior)) => {
            // A slug is derived from the task's first sentence, capped at 40 chars, so
            // "Fix the bug. In auth" and "Fix the bug. In the parser" collide silently
            // (spec 19 — "Task identity"). For a human typing an interactive prompt that
            // is rare; for free-text filed on a phone, short generic first sentences are
            // the NORMAL case. Without this check the second run adopts the first's
            // approved artifacts as its own and then overwrites them.
            //
            // `state.json` has always recorded the task text. It was simply never read back.
            if let Some(conflict) = task_conflict(&prior.task, &state.task) {
                return Err(sc_proto::DcError::Eval(format!(
                    "{} already holds a different task.\n  there: {conflict}\n  here:  {}\n\
                     Both slugify the same way. Rename one, or point this run at another \
                     directory — continuing would overwrite the other task's approved design.",
                    art_dir.display(),
                    first_line_of(&state.task),
                )));
            }

            for a in prior.approved() {
                state.set(a.clone());
                state.approve(a.phase);
                // Surface the reused artifact to the UI so the chat shows the approved design, not
                // a blank jump to the build.
                on_phase(a.phase, &a.content);
            }

            // Restore the pending DRAFT too, not just the approved history (spec 19). A phase that
            // generated cleanly and was saved, but whose gate was never answered because the
            // machine rebooted overnight, would otherwise be discarded and regenerated — so the
            // developer approving in the morning is shown a *different* artifact than the one they
            // were looking at last night. That is corrosive for something pitched as "come back to
            // a drafted spec", and it wastes the model call that produced it.
            //
            // The draft is re-gated, not adopted as approved: it was never signed off, and only a
            // human may do that. It is held aside rather than written into `state`, because
            // `next_phase()` would then have to decide whether an un-approved artifact counts as
            // "done" — and the loop must both re-offer it AND still stop there.
            if let Some(draft) = prior.pending_draft() {
                on_phase(draft.phase, &draft.content);
                resumed_draft = Some(draft.clone());
            }

            // Send-back notes are grounding for the regeneration they asked for, so they must
            // outlive a restart too. Persisted all along, they were simply never copied onto the
            // resuming state — so a phase sent back with "make it event-driven" came back
            // regenerated without ever having seen the note.
            for phase in Phase::ALL {
                if let Some(notes) = prior.feedback(phase) {
                    state.set_feedback(phase, notes);
                }
            }

            // The frozen contract tests are part of the approved contract, so they survive a
            // resume. Starting empty here let a resumed run rewrite the tests a human approved
            // (spec 19 — "a correctness bug, not a papercut").
            test_files = prior.test_files().to_vec();
            state.set_test_files(test_files.clone());

            // Adopt the generation we resumed from, or the first save would look like a
            // stale writer to its own predecessor and be refused (spec 19). We hold the
            // lease, so this is a continuation of that state rather than a race with it.
            state.adopt_generation(prior.generation());
        }
        Ok(None) => {}
        Err(e) => {
            return Err(sc_proto::DcError::Eval(format!(
                "{} could not be read: {e}. It holds this run's approved design, so starting \
                 over would silently discard it — move it aside to begin fresh.",
                art_dir.join("state.json").display(),
            )))
        }
    }
    // Detect the project's language once, so every phase prompt speaks it (a Rust cargo repo
    // gets Rust rules, not the Python/Flask default). Derived from the workspace, not stored in
    // the serializable state.
    let stack = ProjectStack::detect(workspace);

    // Adopt an existing feature spec instead of regenerating it. When the task references a real
    // `specs/<slug>/*.md` (or legacy `PLAN-*.md`), that file already IS the approved spec —
    // Purpose/Requirements/Scenarios and all. Regenerating a fresh Specs phase from it produces a
    // near-duplicate that can DRIFT from what the user approved, and burns a gate click. So pre-seed
    // the Specs artifact from the real spec body and approve it: `next_phase()` then skips Specs and
    // the loop opens at Architecture, while `is_complete()` stays satisfiable (Specs is approved).
    // When there's no referenced spec (the raw-task / Python eval-ladder flow), this is a no-op and
    // the Specs phase generates and gates exactly as before. Pass the RAW `task`, not the grounded
    // string — `referenced_plan` parses the original file token.
    if let Some((_name, spec_body)) = referenced_plan(task, workspace) {
        let spec_body = spec_body.trim();
        if !spec_body.is_empty() {
            state.set(crate::state::Artifact::draft(Phase::Specs, spec_body));
            state.approve(Phase::Specs);
            on_phase(Phase::Specs, spec_body); // still surface it to the UI as the Specs artifact
            save_state(&mut state)?;
        }
    }

    while let Some(phase) = state.next_phase() {
        // A draft restored from a parked run is put back to the human as-is rather than
        // regenerated (spec 19): the whole point is that they approve the artifact they were
        // already shown, not a fresh one. Taken once — `resumed_draft` is cleared here — so a
        // send-back to this phase regenerates normally.
        let artifact = match resumed_draft.take().filter(|a| a.phase == phase) {
            Some(draft) => draft,
            None => {
                // Forward each streamed token tagged with its phase, so the caller (the desktop
                // chat panel) can watch the reply type live and know which phase is speaking — a
                // slow phase used to sit frozen with no sign of life.
                generate_phase(orchestrator, phase, &state, think, stack, &mut |delta| {
                    on_token(phase, delta)
                })
            }
        };
        // Fail loudly on an empty artifact (after the engine's retries) rather than
        // chaining a broken plan downstream — the usual cause is a dead/unreachable
        // orchestrator backend (spec 00 — fail clearly, don't corrupt silently).
        if artifact.content.trim().is_empty() {
            return Err(sc_proto::DcError::Eval(format!(
                "workflow: the {} phase produced no content — is the orchestrator backend up?",
                phase.title()
            )));
        }
        on_phase(phase, &artifact.content);
        // Persist as a draft first, so the gate (and a human editing the file for a
        // Revise) is looking at exactly what's on disk.
        state.set(artifact);
        save_state(&mut state)?;

        match gate.decide(phase, state.artifact(phase).expect("just set")) {
            Decision::Approve => {}
            Decision::Revise => {
                // The human edited the artifact file on disk; re-read it as the
                // accepted content. Fall back to the draft if the file is gone.
                let fname = if openspec_names {
                    phase.openspec_filename().to_string()
                } else {
                    phase.filename()
                };
                let edited = std::fs::read_to_string(art_dir.join(fname))
                    .unwrap_or_else(|_| artifact_content(&state, phase));
                state.set(crate::state::Artifact::draft(phase, edited));
            }
            Decision::SendBack { target, notes } => {
                // Bounce to an earlier (or this) phase: drop it and everything
                // downstream so they regenerate from the revised upstream. Feedback
                // notes ground the regeneration.
                state.invalidate_from(target);
                if let Some(notes) = notes {
                    state.set_feedback(target, notes);
                }
                // Test files written from a now-dropped coverage plan are stale.
                // Cleared BEFORE the save, or the stale contract is what a resume
                // would pick back up.
                if target.index() <= Phase::StageBreakdown.index() {
                    test_files.clear();
                    state.set_test_files(Vec::new());
                }
                save_state(&mut state)?;
                continue;
            }
            Decision::Abort => {
                aborted = true;
                break;
            }
        }

        // Accepted (Approve or Revise): freeze it as grounding for the next phase.
        state.approve(phase);
        save_state(&mut state)?;

        // After the coverage plan is approved, have workers write the tests so
        // they exist on disk for the implementation phases to target. Skipped in the
        // plan-only mode (Execute produces a design, not a frozen test contract).
        if phase == Phase::StageBreakdown && !mode.skip_tests {
            let coverage = crate::coverage::parse_coverage(&artifact_content(&state, phase));
            let written = crate::testwriter::write_tests(worker, &coverage);
            test_files = crate::testwriter::persist_tests(workspace, &written)?;
            // Persist the frozen contract alongside the artifacts. Held only in
            // memory, it was lost on any resume — silently unfreezing the tests a
            // human had just approved (spec 19).
            state.set_test_files(test_files.clone());
            save_state(&mut state)?;
        }

        // Stop-at-phase (plan-only stops once the stage breakdown is approved): the design is
        // done and the user reviews before anything is built. Downstream phases are simply not
        // generated — the state holds the approved-so-far chain.
        if mode.stop_after == Some(phase) {
            break;
        }
    }

    let board = board_from(&state, &test_files, stack);
    Ok(WorkflowOutcome {
        state,
        board,
        test_files,
        aborted,
    })
}

/// The first line of a task, trimmed — what a human recognises it by, and what the
/// slug is derived from.
///
/// Grounding *appends* to the task (the plan body, file contents), so the original
/// text is always the prefix and the first line survives intact. That is what makes
/// a stored task comparable to a fresh one at all.
fn first_line_of(task: &str) -> &str {
    task.lines().next().unwrap_or("").trim()
}

/// Are these two tasks different enough that sharing a directory would be a
/// collision? Returns the stored task's first line when so.
///
/// Compared on the **full first line**, not on the first sentence. Comparing
/// sentences was tried and is exactly wrong: two tasks agreeing there and
/// differing after — "Fix the bug. In auth" versus "Fix the bug. In the parser" —
/// *is* the collision spec 19 describes, since the slug is cut at the first
/// sentence. Treating that as legitimate defeats the entire check.
///
/// A stored task that is a prefix of ours, or the reverse, is the same run
/// continuing with more grounding attached rather than a conflict — grounding
/// appends, so the original text is always the prefix.
pub(super) fn task_conflict<'a>(stored: &'a str, current: &str) -> Option<&'a str> {
    let a = first_line_of(stored);
    let b = first_line_of(current);
    if a.is_empty() || b.is_empty() || a.starts_with(b) || b.starts_with(a) {
        return None;
    }
    Some(a)
}
