//! The pipeline driver: four public entry points over one gated loop.
//!
//! The gate is harness-owned — the loop, not the model, applies each
//! [`Decision`], so a model can never self-approve or skip a phase.

use std::path::Path;

use sc_model::ModelBackend;
use sc_proto::Result;

use crate::engine::generate_phase;
use crate::gate::{AutoApprove, Decision, Gate};
use crate::phase::Phase;
use crate::policy::ThinkPolicy;
use crate::stack::ProjectStack;
use crate::state::WorkflowState;

use super::board::{artifact_content, board_from};
use super::ground::{ground_task, referenced_plan};
use super::mode::{WorkflowMode, WorkflowOutcome};

/// Run the whole pipeline autonomously against `workspace`, approving every phase
/// (no human gate). This is the default mode: it proves the spec → … →
/// decomposition chain produces a board the swarm consumes. Delegates to
/// [`run_workflow_gated`] with the [`AutoApprove`] gate.
pub fn run_workflow(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
) -> Result<WorkflowOutcome> {
    run_workflow_gated(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        on_phase,
        &AutoApprove,
    )
}

/// Drive the pipeline against `workspace`, consulting `gate` at every phase
/// boundary (spec 09's macro checkpoint). Each phase is generated by `orchestrator`
/// (T1) from the prior *approved* artifacts and persisted to disk *as a draft*
/// before the gate sees it — so an interactive gate can have the human read (and,
/// for Revise, edit) the on-disk file. The gate's [`Decision`] is then applied by
/// the harness:
///
/// - **Approve** — accept the draft and advance.
/// - **Revise** — re-read the (human-edited) file from disk, accept that.
/// - **Send back** — drop this phase and everything downstream, regenerate from the
///   target phase (`invalidate_from`).
/// - **Abort** — stop now; approved artifacts are kept and the outcome is flagged.
///
/// Only an *approved* Phase-4 (stage-breakdown) artifact triggers the worker test
/// writing, so revised coverage plans drive the frozen tests and a send-back that
/// later re-approves Phase 4 regenerates them.
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_gated(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    run_workflow_moded(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        WorkflowMode::full_tdd(),
        on_phase,
        gate,
    )
}

/// The core pipeline driver, parameterized by [`WorkflowMode`] — the full-TDD default and the
/// plan-only Execute flow share this one loop. `mode.stop_after` ends the run once that phase
/// is approved (plan-only stops at the stage breakdown); `mode.skip_tests` suppresses the
/// worker test-writing (plan-only produces a design, not a frozen contract).
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_moded(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    mode: WorkflowMode,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    // Default artifact layout: `.smart-coder/plan/` with numbered filenames. This entry point
    // has no live-token consumer (the CLI/examples stream to the plan panel via `on_phase`), so
    // pass a no-op token callback.
    run_workflow_moded_to(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        mode,
        on_phase,
        gate,
        None,
        false,
        &mut |_p, _d| {},
    )
}

/// Like [`run_workflow_moded`], but persists phase artifacts to `artifact_dir` (default
/// `.smart-coder/plan/` when `None`) with either numbered or OpenSpec filenames — so the staged
/// build can land its design in `specs/<slug>/` (spec.md, architecture.md, …) beside the spec.
///
/// `on_token(phase, delta)` receives each streamed content delta of the phase currently
/// generating, so a live UI can render the reply token-by-token (the staged run reads as alive,
/// not frozen). Callers that don't want the live view pass a no-op `&mut |_p, _d| {}`.
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_moded_to(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    mode: WorkflowMode,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
    artifact_dir: Option<&Path>,
    openspec_names: bool,
    on_token: &mut dyn FnMut(Phase, &str),
) -> Result<WorkflowOutcome> {
    // The directory phase artifacts are written to (and re-read on Revise).
    let art_dir = artifact_dir
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| crate::state::plan_dir(workspace));
    let save_state = |state: &WorkflowState| crate::state::save_to(&art_dir, state, openspec_names);
    // Ground the task in reality BEFORE the first phase: a workflow phase is a direct model call
    // that otherwise sees only the task string — so with just "implement PLAN-lakes.md" the
    // orchestrator designed a generic module tree that ignored the plan AND the real files
    // (observed live 2026-07-14: it invented src/lakes/*.rs, never touching the plan's
    // gen/terrain.rs / render.rs). Inject the plan's full body and a survey of the files that
    // actually exist, so every phase designs against THIS plan and THIS codebase.
    let grounded = ground_task(task, workspace);
    let mut state = WorkflowState::new(grounded);
    let mut test_files = Vec::new();
    let mut aborted = false;

    // Resume from an approved breakdown instead of regenerating it. A **Build** reuses the same
    // task (and thus the same `art_dir`) a prior **Breakdown** ran, so its approved design phases
    // are already on disk in `state.json`. Adopt those approved artifacts up front: `next_phase()`
    // then skips straight past specs/architecture/layout/stage-breakdown to the build, instead of
    // re-designing and re-gating them (the bug where clicking Build re-did the architecture).
    //
    // Only APPROVED phases are adopted — a draft/unapproved phase (e.g. an aborted breakdown)
    // still regenerates and gates normally. We copy them onto the freshly-grounded `state` (rather
    // than adopting the loaded state wholesale) so the current run's grounding/feedback apply to
    // anything that does regenerate.
    if let Ok(Some(prior)) = crate::state::load_from(&art_dir) {
        for a in prior.approved() {
            state.set(a.clone());
            state.approve(a.phase);
            // Surface the reused artifact to the UI so the chat shows the approved design, not a
            // blank jump to the build.
            on_phase(a.phase, &a.content);
        }
    }
    // Detect the project's language once, so every phase prompt speaks it (a Rust cargo repo
    // gets Rust rules, not the Python/Flask default). Derived from the workspace, not stored in
    // the serializable state.
    let stack = ProjectStack::detect(workspace);

    // Adopt an existing feature spec instead of regenerating it. When the task references a real
    // `specs/<slug>/*.md` (or legacy `PLAN-*.md`), that file already IS the approved spec —
    // Purpose/Requirements/Scenarios and all. Regenerating a fresh Specs phase from it produces a
    // near-duplicate that can DRIFT from what the user approved, and burns a gate click. So pre-seed
    // the Specs artifact from the real spec body and approve it: `next_phase()` then skips Specs and
    // the loop opens at Architecture, while `is_complete()` stays satisfiable (Specs is approved).
    // When there's no referenced spec (the raw-task / Python eval-ladder flow), this is a no-op and
    // the Specs phase generates and gates exactly as before. Pass the RAW `task`, not the grounded
    // string — `referenced_plan` parses the original file token.
    if let Some((_name, spec_body)) = referenced_plan(task, workspace) {
        let spec_body = spec_body.trim();
        if !spec_body.is_empty() {
            state.set(crate::state::Artifact::draft(Phase::Specs, spec_body));
            state.approve(Phase::Specs);
            on_phase(Phase::Specs, spec_body); // still surface it to the UI as the Specs artifact
            save_state(&state)?;
        }
    }

    while let Some(phase) = state.next_phase() {
        // Forward each streamed token tagged with its phase, so the caller (the desktop chat
        // panel) can watch the reply type live and know which phase is speaking — a slow phase
        // used to sit frozen with no sign of life.
        let artifact = generate_phase(orchestrator, phase, &state, think, stack, &mut |delta| {
            on_token(phase, delta)
        });
        // Fail loudly on an empty artifact (after the engine's retries) rather than
        // chaining a broken plan downstream — the usual cause is a dead/unreachable
        // orchestrator backend (spec 00 — fail clearly, don't corrupt silently).
        if artifact.content.trim().is_empty() {
            return Err(sc_proto::DcError::Eval(format!(
                "workflow: the {} phase produced no content — is the orchestrator backend up?",
                phase.title()
            )));
        }
        on_phase(phase, &artifact.content);
        // Persist as a draft first, so the gate (and a human editing the file for a
        // Revise) is looking at exactly what's on disk.
        state.set(artifact);
        save_state(&state)?;

        match gate.decide(phase, state.artifact(phase).expect("just set")) {
            Decision::Approve => {}
            Decision::Revise => {
                // The human edited the artifact file on disk; re-read it as the
                // accepted content. Fall back to the draft if the file is gone.
                let fname = if openspec_names {
                    phase.openspec_filename().to_string()
                } else {
                    phase.filename()
                };
                let edited = std::fs::read_to_string(art_dir.join(fname))
                    .unwrap_or_else(|_| artifact_content(&state, phase));
                state.set(crate::state::Artifact::draft(phase, edited));
            }
            Decision::SendBack { target, notes } => {
                // Bounce to an earlier (or this) phase: drop it and everything
                // downstream so they regenerate from the revised upstream. Feedback
                // notes ground the regeneration.
                state.invalidate_from(target);
                if let Some(notes) = notes {
                    state.set_feedback(target, notes);
                }
                save_state(&state)?;
                // Test files written from a now-dropped coverage plan are stale.
                if target.index() <= Phase::StageBreakdown.index() {
                    test_files.clear();
                }
                continue;
            }
            Decision::Abort => {
                aborted = true;
                break;
            }
        }

        // Accepted (Approve or Revise): freeze it as grounding for the next phase.
        state.approve(phase);
        save_state(&state)?;

        // After the coverage plan is approved, have workers write the tests so
        // they exist on disk for the implementation phases to target. Skipped in the
        // plan-only mode (Execute produces a design, not a frozen test contract).
        if phase == Phase::StageBreakdown && !mode.skip_tests {
            let coverage = crate::coverage::parse_coverage(&artifact_content(&state, phase));
            let written = crate::testwriter::write_tests(worker, &coverage);
            test_files = crate::testwriter::persist_tests(workspace, &written)?;
        }

        // Stop-at-phase (plan-only stops once the stage breakdown is approved): the design is
        // done and the user reviews before anything is built. Downstream phases are simply not
        // generated — the state holds the approved-so-far chain.
        if mode.stop_after == Some(phase) {
            break;
        }
    }

    let board = board_from(&state, &test_files, stack);
    Ok(WorkflowOutcome {
        state,
        board,
        test_files,
        aborted,
    })
}
