//! The autonomous workflow runner (spec 09): drive the pipeline end to end,
//! auto-approving every gate, persisting each artifact, and emerging with the
//! swarm-ready subtask board from the final phase.
//!
//! Human checkpoints (approve/revise/send-back/abort) layer on top of this later;
//! here every gate is auto-approved so we can prove the spec → … → decomposition
//! chain produces a board the swarm consumes.

use std::path::Path;

use dc_model::ModelBackend;
use dc_proto::Result;
use dc_swarm::{parse_subtasks, TaskBoard};

use crate::engine::generate_phase;
use crate::phase::Phase;
use crate::state::{save, WorkflowState};

/// What a completed workflow yields.
#[derive(Debug)]
pub struct WorkflowOutcome {
    /// The full artifact chain (all approved), persisted under the plan dir.
    pub state: WorkflowState,
    /// The subtask board parsed from the final (work-decomposition) phase — the
    /// swarm's input. Empty board if the model produced nothing parseable.
    pub board: TaskBoard,
}

/// Run the whole pipeline autonomously against `workspace`, persisting after every
/// phase. Each phase is generated by `orchestrator` from the prior approved
/// artifacts and immediately approved (no human gate in this mode).
pub fn run_workflow(
    orchestrator: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    on_phase: &dyn Fn(Phase, &str),
) -> Result<WorkflowOutcome> {
    let mut state = WorkflowState::new(task);

    while let Some(phase) = state.next_phase() {
        let artifact = generate_phase(orchestrator, phase, &state);
        on_phase(phase, &artifact.content);
        state.set(artifact);
        // Autonomous: approve immediately so the next phase can ground on it.
        state.approve(phase);
        save(workspace, &state)?;
    }

    let board = board_from(&state);
    Ok(WorkflowOutcome { state, board })
}

/// Parse the work-decomposition artifact into the swarm's [`TaskBoard`] (spec 09
/// → spec 08 input contract). The same tolerant parser the orchestrator uses, so
/// the workflow's decomposition and a direct swarm decomposition agree.
fn board_from(state: &WorkflowState) -> TaskBoard {
    let subtasks = state
        .artifact(Phase::WorkDecomposition)
        .map(|a| parse_subtasks(&a.content))
        .unwrap_or_default();
    TaskBoard::new(subtasks)
}

#[cfg(test)]
mod tests {
    use super::*;
    use dc_model::{Capabilities, GenerateRequest, GenerateResponse, ToolCalling};
    use std::sync::Mutex;

    /// A backend that answers each phase by matching its system prompt, and emits a
    /// valid subtask array for the decomposition phase.
    struct PhaseScripted {
        replies: Mutex<Vec<(&'static str, &'static str)>>,
    }
    impl ModelBackend for PhaseScripted {
        fn name(&self) -> &str {
            "phase-scripted"
        }
        fn capabilities(&self) -> Capabilities {
            Capabilities {
                max_context_tokens: 8192,
                tool_calling: ToolCalling::None,
                on_device: false,
            }
        }
        fn generate(&self, req: &GenerateRequest) -> dc_proto::Result<GenerateResponse> {
            let instr = req
                .messages
                .iter()
                .map(|m| m.content.as_str())
                .collect::<Vec<_>>()
                .join("\n");
            let replies = self.replies.lock().unwrap();
            for (key, body) in replies.iter() {
                if instr.contains(key) {
                    return Ok(GenerateResponse {
                        content: body.to_string(),
                    });
                }
            }
            Ok(GenerateResponse {
                content: "(nothing)".to_string(),
            })
        }
    }

    fn temp(tag: &str) -> std::path::PathBuf {
        let n = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let d = std::env::temp_dir().join(format!("dc-wf-run-{tag}-{n}"));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn runs_all_phases_and_emits_a_board() {
        let backend = PhaseScripted {
            replies: Mutex::new(vec![
                ("crisp spec", "# Specs\ngoals"),
                ("high-level architecture", "# Architecture\nshape"),
                ("concrete project layout", "# Layout\nfiles"),
                ("incremental stages", "# Stages\ntests first"),
                ("ordered plan", "# Plan\nsteps"),
                (
                    "INDEPENDENT subtasks",
                    r#"[{"id":"t1","goal":"do a","files":["a.py"]},{"id":"t2","goal":"do b","files":["b.py"]}]"#,
                ),
            ]),
        };
        let ws = temp("all");
        let seen = std::cell::RefCell::new(Vec::new());
        let outcome =
            run_workflow(&backend, "build it", &ws, &|p, _| seen.borrow_mut().push(p)).unwrap();

        // All six phases ran, in order, and the workflow is complete.
        assert_eq!(seen.into_inner(), Phase::ALL.to_vec());
        assert!(outcome.state.is_complete());
        // The decomposition produced a swarm board with two subtasks.
        assert_eq!(outcome.board.len(), 2);
        // Artifacts persisted as reviewable Markdown.
        let arch = std::fs::read_to_string(crate::state::plan_dir(&ws).join("02-architecture.md"))
            .unwrap();
        assert!(arch.contains("shape"));
        let _ = std::fs::remove_dir_all(&ws);
    }
}
