//! The workflow runner (spec 09): drive the pipeline end to end, gating each phase
//! boundary through a [`Gate`], persisting each artifact, and emerging with the
//! swarm-ready subtask board from the final phase.
//!
//! Two gating modes share one loop. The autonomous default ([`run_workflow`])
//! approves every phase via [`AutoApprove`]; an interactive run supplies a gate that
//! reads a human's approve/revise/send-back/abort decision at each checkpoint. The
//! gate is harness-owned — the loop, not the model, applies the decision.

use std::path::Path;

use dc_model::ModelBackend;
use dc_proto::Result;
use dc_swarm::{parse_subtasks, TaskBoard};

use crate::engine::generate_phase;
use crate::gate::{AutoApprove, Decision, Gate};
use crate::phase::Phase;
use crate::policy::ThinkPolicy;
use crate::state::{plan_dir, save, WorkflowState};

/// What a completed workflow yields.
#[derive(Debug)]
pub struct WorkflowOutcome {
    /// The full artifact chain (all approved), persisted under the plan dir.
    pub state: WorkflowState,
    /// The subtask board parsed from the final (work-decomposition) phase — the
    /// swarm's input. Empty board if the model produced nothing parseable.
    pub board: TaskBoard,
    /// The test files the workers wrote from the Phase-4 coverage plan, already
    /// persisted to `workspace`. These are the frozen contract the implementation
    /// swarm must satisfy.
    pub test_files: Vec<String>,
    /// Whether the human aborted at a checkpoint. When true the pipeline stopped
    /// early: `state` holds the approved-so-far artifacts (kept, per spec 09) and
    /// `board`/`test_files` reflect only what was reached.
    pub aborted: bool,
}

/// Run the whole pipeline autonomously against `workspace`, approving every phase
/// (no human gate). This is the default mode: it proves the spec → … →
/// decomposition chain produces a board the swarm consumes. Delegates to
/// [`run_workflow_gated`] with the [`AutoApprove`] gate.
pub fn run_workflow(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
) -> Result<WorkflowOutcome> {
    run_workflow_gated(
        orchestrator,
        worker,
        task,
        workspace,
        think,
        on_phase,
        &AutoApprove,
    )
}

/// Drive the pipeline against `workspace`, consulting `gate` at every phase
/// boundary (spec 09's macro checkpoint). Each phase is generated by `orchestrator`
/// (T1) from the prior *approved* artifacts and persisted to disk *as a draft*
/// before the gate sees it — so an interactive gate can have the human read (and,
/// for Revise, edit) the on-disk file. The gate's [`Decision`] is then applied by
/// the harness:
///
/// - **Approve** — accept the draft and advance.
/// - **Revise** — re-read the (human-edited) file from disk, accept that.
/// - **Send back** — drop this phase and everything downstream, regenerate from the
///   target phase (`invalidate_from`).
/// - **Abort** — stop now; approved artifacts are kept and the outcome is flagged.
///
/// Only an *approved* Phase-4 (stage-breakdown) artifact triggers the worker test
/// writing, so revised coverage plans drive the frozen tests and a send-back that
/// later re-approves Phase 4 regenerates them.
#[allow(clippy::too_many_arguments)]
pub fn run_workflow_gated(
    orchestrator: &dyn ModelBackend,
    worker: &dyn ModelBackend,
    task: &str,
    workspace: &Path,
    think: ThinkPolicy,
    on_phase: &dyn Fn(Phase, &str),
    gate: &dyn Gate,
) -> Result<WorkflowOutcome> {
    let mut state = WorkflowState::new(task);
    let mut test_files = Vec::new();
    let mut aborted = false;

    while let Some(phase) = state.next_phase() {
        let artifact = generate_phase(orchestrator, phase, &state, think);
        // Fail loudly on an empty artifact (after the engine's retries) rather than
        // chaining a broken plan downstream — the usual cause is a dead/unreachable
        // orchestrator backend (spec 00 — fail clearly, don't corrupt silently).
        if artifact.content.trim().is_empty() {
            return Err(dc_proto::DcError::Eval(format!(
                "workflow: the {} phase produced no content — is the orchestrator backend up?",
                phase.title()
            )));
        }
        on_phase(phase, &artifact.content);
        // Persist as a draft first, so the gate (and a human editing the file for a
        // Revise) is looking at exactly what's on disk.
        state.set(artifact);
        save(workspace, &state)?;

        match gate.decide(phase, state.artifact(phase).expect("just set")) {
            Decision::Approve => {}
            Decision::Revise => {
                // The human edited the artifact file on disk; re-read it as the
                // accepted content. Fall back to the draft if the file is gone.
                let edited = std::fs::read_to_string(plan_dir(workspace).join(phase.filename()))
                    .unwrap_or_else(|_| artifact_content(&state, phase));
                state.set(crate::state::Artifact::draft(phase, edited));
            }
            Decision::SendBack { target, notes } => {
                // Bounce to an earlier (or this) phase: drop it and everything
                // downstream so they regenerate from the revised upstream. Feedback
                // notes ground the regeneration.
                state.invalidate_from(target);
                if let Some(notes) = notes {
                    state.set_feedback(target, notes);
                }
                save(workspace, &state)?;
                // Test files written from a now-dropped coverage plan are stale.
                if target.index() <= Phase::StageBreakdown.index() {
                    test_files.clear();
                }
                continue;
            }
            Decision::Abort => {
                aborted = true;
                break;
            }
        }

        // Accepted (Approve or Revise): freeze it as grounding for the next phase.
        state.approve(phase);
        save(workspace, &state)?;

        // After the coverage plan is approved, have workers write the tests so
        // they exist on disk for the implementation phases to target.
        if phase == Phase::StageBreakdown {
            let coverage = crate::coverage::parse_coverage(&artifact_content(&state, phase));
            let written = crate::testwriter::write_tests(worker, &coverage);
            test_files = crate::testwriter::persist_tests(workspace, &written)?;
        }
    }

    let board = board_from(&state, &test_files);
    Ok(WorkflowOutcome {
        state,
        board,
        test_files,
        aborted,
    })
}

fn artifact_content(state: &WorkflowState, phase: Phase) -> String {
    state
        .artifact(phase)
        .map(|a| a.content.clone())
        .unwrap_or_default()
}

/// Parse the work-decomposition artifact into the swarm's [`TaskBoard`] (spec 09
/// → spec 08 input contract), then drop any non-implementation subtasks the model
/// slipped in: ones that target a frozen test file, or that name no files at all
/// (e.g. a "run the tests" step — the harness verifies, that's not worker work).
/// Tests are already written and frozen; the swarm only implements.
fn board_from(state: &WorkflowState, test_files: &[String]) -> TaskBoard {
    let is_test = |f: &str| {
        let n = f.replace('\\', "/");
        test_files.iter().any(|t| t.replace('\\', "/") == n)
    };
    let subtasks: Vec<_> = state
        .artifact(Phase::WorkDecomposition)
        .map(|a| parse_subtasks(&a.content))
        .unwrap_or_default()
        .into_iter()
        .filter(|s| !s.files.is_empty() && !s.files.iter().all(|f| is_test(f)))
        .collect();
    TaskBoard::new(subtasks)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::Artifact;
    use dc_model::{Capabilities, GenerateRequest, GenerateResponse, ToolCalling};
    use std::sync::Mutex;

    /// A backend that answers each phase by matching its system prompt, and emits a
    /// valid subtask array for the decomposition phase.
    struct PhaseScripted {
        replies: Mutex<Vec<(&'static str, &'static str)>>,
    }
    impl ModelBackend for PhaseScripted {
        fn name(&self) -> &str {
            "phase-scripted"
        }
        fn capabilities(&self) -> Capabilities {
            Capabilities {
                max_context_tokens: 8192,
                tool_calling: ToolCalling::None,
                on_device: false,
            }
        }
        fn generate(&self, req: &GenerateRequest) -> dc_proto::Result<GenerateResponse> {
            let instr = req
                .messages
                .iter()
                .map(|m| m.content.as_str())
                .collect::<Vec<_>>()
                .join("\n");
            let replies = self.replies.lock().unwrap();
            for (key, body) in replies.iter() {
                if instr.contains(key) {
                    return Ok(GenerateResponse {
                        content: body.to_string(),
                    });
                }
            }
            Ok(GenerateResponse {
                content: "(nothing)".to_string(),
            })
        }
    }

    fn temp(tag: &str) -> std::path::PathBuf {
        let n = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let d = std::env::temp_dir().join(format!("dc-wf-run-{tag}-{n}"));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn runs_all_phases_and_emits_a_board() {
        let backend = PhaseScripted {
            replies: Mutex::new(vec![
                ("crisp spec", "# Specs\ngoals"),
                ("high-level architecture", "# Architecture\nshape"),
                ("concrete project layout", "# Layout\nfiles"),
                (
                    "plan the TESTS",
                    r#"[{"file":"test_a.py","covers":"a works"}]"#,
                ),
                // The test-writer worker call (system prompt says "You write a runnable unit-test file").
                ("pytest test file", "def test_a():\n    assert a() == 1"),
                ("ordered plan", "# Plan\nsteps"),
                (
                    "INDEPENDENT subtasks",
                    r#"[{"id":"t1","goal":"do a","files":["a.py"]},{"id":"t2","goal":"do b","files":["b.py"]}]"#,
                ),
            ]),
        };
        let ws = temp("all");
        let seen = std::cell::RefCell::new(Vec::new());
        // Same backend stands in for both orchestrator and worker here.
        let outcome = run_workflow(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|p, _| seen.borrow_mut().push(p),
        )
        .unwrap();

        // All six phases ran, in order, and the workflow is complete.
        assert_eq!(seen.into_inner(), Phase::ALL.to_vec());
        assert!(outcome.state.is_complete());
        // The decomposition produced a swarm board with two subtasks.
        assert_eq!(outcome.board.len(), 2);
        // A worker wrote the test file from the coverage plan, and it's on disk.
        assert_eq!(outcome.test_files, vec!["test_a.py"]);
        let test_body = std::fs::read_to_string(ws.join("test_a.py")).unwrap();
        assert!(test_body.contains("def test_a"));
        // Artifacts persisted as reviewable Markdown.
        let arch = std::fs::read_to_string(crate::state::plan_dir(&ws).join("02-architecture.md"))
            .unwrap();
        assert!(arch.contains("shape"));
        let _ = std::fs::remove_dir_all(&ws);
    }

    /// A full scripted backend that answers every phase + the test-writer worker.
    fn full_backend() -> PhaseScripted {
        PhaseScripted {
            replies: Mutex::new(vec![
                ("crisp spec", "# Specs\ngoals"),
                ("high-level architecture", "# Architecture\nshape"),
                ("concrete project layout", "# Layout\nfiles"),
                (
                    "plan the TESTS",
                    r#"[{"file":"test_a.py","covers":"a works"}]"#,
                ),
                ("pytest test file", "def test_a():\n    assert a() == 1"),
                ("ordered plan", "# Plan\nsteps"),
                (
                    "INDEPENDENT subtasks",
                    r#"[{"id":"t1","goal":"do a","files":["a.py"]}]"#,
                ),
            ]),
        }
    }

    /// A gate that replays a fixed script of decisions, one per checkpoint visit,
    /// recording which phases it was asked about.
    struct ScriptedGate {
        decisions: Mutex<std::collections::VecDeque<Decision>>,
        seen: Mutex<Vec<Phase>>,
    }
    impl ScriptedGate {
        fn new(decisions: Vec<Decision>) -> Self {
            Self {
                decisions: Mutex::new(decisions.into()),
                seen: Mutex::new(Vec::new()),
            }
        }
    }
    impl Gate for ScriptedGate {
        fn decide(&self, phase: Phase, _artifact: &Artifact) -> Decision {
            self.seen.lock().unwrap().push(phase);
            // Default to Approve once the script is exhausted, so a short script
            // just gates the first few phases and lets the rest sail through.
            self.decisions
                .lock()
                .unwrap()
                .pop_front()
                .unwrap_or(Decision::Approve)
        }
    }

    #[test]
    fn auto_approve_path_matches_run_workflow() {
        // run_workflow_gated with AutoApprove behaves exactly like run_workflow.
        let backend = full_backend();
        let ws = temp("gated-auto");
        let outcome = run_workflow_gated(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|_, _| {},
            &AutoApprove,
        )
        .unwrap();
        assert!(outcome.state.is_complete());
        assert!(!outcome.aborted);
        assert_eq!(outcome.board.len(), 1);
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn abort_stops_early_and_keeps_approved_artifacts() {
        let backend = full_backend();
        let ws = temp("gated-abort");
        // Approve specs + architecture, then abort at the layout checkpoint.
        let gate = ScriptedGate::new(vec![Decision::Approve, Decision::Approve, Decision::Abort]);
        let outcome = run_workflow_gated(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|_, _| {},
            &gate,
        )
        .unwrap();

        assert!(outcome.aborted);
        assert!(!outcome.state.is_complete());
        // The two approved phases survive; the aborted layout draft does not freeze.
        assert!(outcome.state.artifact(Phase::Specs).unwrap().is_approved());
        assert!(outcome
            .state
            .artifact(Phase::Architecture)
            .unwrap()
            .is_approved());
        assert!(!outcome.state.artifact(Phase::Layout).unwrap().is_approved());
        // Never reached decomposition, so no board.
        assert_eq!(outcome.board.len(), 0);
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn revise_reads_the_edited_file_from_disk() {
        let backend = full_backend();
        let ws = temp("gated-revise");
        // A gate that, on the very first (Specs) checkpoint, edits the on-disk file
        // and asks for a Revise; everything else approves.
        struct EditingGate {
            ws: std::path::PathBuf,
            edited: Mutex<bool>,
        }
        impl Gate for EditingGate {
            fn decide(&self, phase: Phase, _a: &Artifact) -> Decision {
                if phase == Phase::Specs && !*self.edited.lock().unwrap() {
                    std::fs::write(
                        plan_dir(&self.ws).join(phase.filename()),
                        "# Specs\nHUMAN EDITED",
                    )
                    .unwrap();
                    *self.edited.lock().unwrap() = true;
                    return Decision::Revise;
                }
                Decision::Approve
            }
        }
        let gate = EditingGate {
            ws: ws.clone(),
            edited: Mutex::new(false),
        };
        let outcome = run_workflow_gated(
            &backend,
            &backend,
            "build it",
            &ws,
            ThinkPolicy::default(),
            &|_, _| {},
            &gate,
        )
        .unwrap();

        // The approved specs artifact is the human's edited content, not the draft.
        let specs = outcome.state.artifact(Phase::Specs).unwrap();
        assert!(specs.is_approved());
        assert!(specs.content.contains("HUMAN EDITED"));
        assert!(outcome.state.is_complete());
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn send_back_regenerates_with_feedback_and_completes() {
        let ws = temp("gated-sendback");
        // Count how many times the architecture phase is generated: a send-back from
        // Layout to Architecture should regenerate it.
        let arch_calls = std::cell::RefCell::new(0u32);
        let saw_feedback = std::cell::RefCell::new(false);
        {
            let backend = full_backend();
            // Gate: approve specs + architecture, then at the Layout checkpoint send
            // back to Architecture with a note. After that, approve everything.
            let gate = ScriptedGate::new(vec![
                Decision::Approve, // specs
                Decision::Approve, // architecture (1st)
                Decision::SendBack {
                    target: Phase::Architecture,
                    notes: Some("make it event-driven".to_string()),
                }, // layout → bounce
            ]);
            // Wrap the backend's generate to count architecture regenerations and
            // detect the feedback note reaching the prompt. We can't easily wrap the
            // trait object, so instead inspect via a custom backend.
            struct CountingBackend<'a> {
                inner: PhaseScripted,
                arch_calls: &'a std::cell::RefCell<u32>,
                saw_feedback: &'a std::cell::RefCell<bool>,
            }
            impl ModelBackend for CountingBackend<'_> {
                fn name(&self) -> &str {
                    "counting"
                }
                fn capabilities(&self) -> Capabilities {
                    self.inner.capabilities()
                }
                fn generate(&self, req: &GenerateRequest) -> dc_proto::Result<GenerateResponse> {
                    let joined: String = req.messages.iter().map(|m| m.content.clone()).collect();
                    if joined.contains("high-level architecture") {
                        *self.arch_calls.borrow_mut() += 1;
                        if joined.contains("make it event-driven") {
                            *self.saw_feedback.borrow_mut() = true;
                        }
                    }
                    self.inner.generate(req)
                }
            }
            let counting = CountingBackend {
                inner: backend,
                arch_calls: &arch_calls,
                saw_feedback: &saw_feedback,
            };
            let outcome = run_workflow_gated(
                &counting,
                &counting,
                "build it",
                &ws,
                ThinkPolicy::default(),
                &|_, _| {},
                &gate,
            )
            .unwrap();
            assert!(outcome.state.is_complete());
            assert!(!outcome.aborted);
        }
        // Architecture was generated twice (initial + after send-back), and the
        // feedback note reached the regeneration prompt.
        assert_eq!(*arch_calls.borrow(), 2);
        assert!(*saw_feedback.borrow());
        let _ = std::fs::remove_dir_all(&ws);
    }
}
